### ISSUE TITLE
[Idea] Move Tests to Mocha + Chai

### ISSUE THREAD

**Issue by marverix** [roddeh/i18njs#10]
It would be nice to start using Mocha + Chai. If you are open to this then I can help with moving.

**Comment by roddeh** [comment]
I am open to this... What would the advantage be?  Right now the tests are very much a "roll-your-own" solution.  However the testing requirements for this lib are fairly simple and there is something to be said for minimising the dependencies.

So, back to the question, if there are clear advantages for this project then let's go for it.

**Comment by marverix** [comment]
Mocha it's very simple and popular test framework. It gives a lot of tools that you can use. It has huge community and plugins. E.g. this is one of my projects (that I'm doing in free time in my job) https://github.com/bitbar/finka-js and as you can see I'm sending data from Mocha to Coveralls (https://coveralls.io/github/bitbar/finka-js?branch=master) and thanks to that I and everyone else can see how well my repo is covered with tests. This is great, because thanks to that tool I was able to detect test cases that I didn't thought about.

**Comment by marverix** [comment]
And moving your tests to Mocha + Chai will be easy.

**Comment by marverix** [comment]
https://github.com/roddeh/i18njs/pull/14
What do you think? :)

**Comment by roddeh** [comment]
Great work, thanks for the contribution.
