### ISSUE TITLE
Contexts not working?

### ISSUE THREAD

**Issue by jmle** [roddeh/i18njs#17]
Hello,

I've been trying the library out and can't seem to get the contexts to work. I have tried with the examples provided in the docs with no luck:

```
{
  "values":{
    "Yes": "Yes",
    "No": "No"
  },
  "contexts":[
    {
      "matches":{
        "gender":"male"
      },
      "values":{
          "%{name} updated their profile": "%{name} updated his profile"
      }
    },
    {
      "matches":{
        "gender":"female"
      },
      "values":{
        "%{name} updated their profile": "%{name} updated her profile"
      }
    }
  ]
}
```
And then:
```
console.log(i18n("%{name} updated their profile",
  {
    name: "Jane"
  },
  {
    gender: "female"
  }
));
```
Which ouputs `Jane updated their profile`. The expected is `Jane updated her profile`, if I'm not mistaken. I have also tried removing the `%{name}` variable, but still not working.

Thank you.

**Comment by roddeh** [comment]
The documentation was perhaps misleading in that it assumes that the values will be "added" to the instance of i18n e.g.

i18n.translator.add(
  {
  "values":{
    "Yes": "Yes",
    "No": "No"
  },
  "contexts":[
    {
      "matches":{
        "gender":"male"
      },
      "values":{
          "%{name} updated their profile":
          "%{name} updated his profile"
      }
    },
    {
      "matches":{
        "gender":"female"
      },
      "values":{
        "%{name} updated their profile":
        "%{name} updated her profile"
      }
    }
  ]
});

Given the issue was closed, I suspect you came to the same solution ;)

Let me know if you continue to have issues.

**Comment by jmle** [comment]
Thank you @roddeh, it was actually something completely unrelated to the library... The docs are quite clear actually. My mistake!

**Comment by roddeh** [comment]
No problem, I hope the library meets your i18n needs!
