### ISSUE TITLE
i18njs as NPM package

### ISSUE THREAD

**Issue by mediafreakch** [roddeh/i18njs#2]
Hey Simon,

Have you considered this awesome library as a package on npmjs.org? Would love to use it on my project, which uses NPM as the package manager.

Edi

**Comment by roddeh** [comment]
Hi Edi, 

Yeah, I should totally get around to doing that.

Tell you what, I will get it up on npm in the next 3 days.  Thanks for the motivational push ;)

Cheers,
Simon

**Comment by mediafreakch** [comment]
Is this it? 

https://www.npmjs.com/package/roddeh-i18n 

Thanks a lot ;)

**Comment by roddeh** [comment]
Yeah, that is it.

Let me know if you have any other questions.

Cheers,
Simon
