### ISSUE TITLE
Package in NPM is outdated (missing TS typings)

### ISSUE THREAD

**Issue by decryphe** [roddeh/i18njs#21]
It would be nice to have an official release of the current repo state as a new version to the NPM registry.

**Comment by roddeh** [comment]
Apologies, this fell through the cracks.  Thanks for the prompt.  I have added the typings and bumped the version to 1.3.

**Comment by decryphe** [comment]
Thanks a lot! Very happy with this package, does exactly what we need and doesn't deliver a lot of unnecessary bloat.

Just a note: As the typings file (*.d.ts) is located in a subfolder, I have to add a shim `shims-i18n.d.ts` in my project root to get the TS compiler to find them:
```TypeScript
declare module "roddeh-i18n" {
  import i18n from "roddeh-i18n/typings";
  export default i18n;
}
```
I'd suggest to add this to the `README.md` of the project and/or the i18njs.com so people are aware of the typings actually existing.
Also: Place a link to this GitHub on i18njs.com?

**Comment by roddeh** [comment]
Glad you are getting value from it.  As you point out, I try to keep it very slim i.e. no dependencies (other than dev).

Reckon you can put in a pull request for the README.md. 

I will also look to update the website to link to the GH.  I should really update the colour scheme of that website too :)
