### ISSUE TITLE
[Idea] Support for num eq null

### ISSUE THREAD

**Issue by marverix** [roddeh/i18njs#4]
Hi,
I'm using your library in couple projects already. Simplicity of this library is just sweet. What I'm missing is support for `num === null`. Scenario? Let's say that I have dynamic translation of sentence that is working on numbers. So my translation is looking like:
```
...
"DEVICES": [
  [null, null, "Some error - please check your syntax"],
  [0, 0, "No devices available"],
  [1, 1, "%n device available"],
  [2, null, "%n devices available"]
],
...
```

With above triplets I can condition and support for example errors if I like. It's just example. The most important stuff is that you don't need to do any other conditions in code - triplet `[null, null, "Text"]` could easly handle it. I have even implemented it already in my copy of your library. If you are interested then I can fork repo and do a PR. Let me know what do you think.

Cheers,
Marek

**Comment by roddeh** [comment]
Hi Marek,

Really glad to hear that you are getting value out of this library. Yes, I like your suggestion for supporting the error case. If you could send through a PR that would be awesome.  Bonus points if your PR could include adding a couple of tests ;)

Thanks,
Simon

**Comment by marverix** [comment]
I did a bit more :)
https://github.com/roddeh/i18njs/pull/5

How about that?
