### ISSUE TITLE
Typescript definitions file

### ISSUE THREAD

**Issue by gregBerthelot** [roddeh/i18njs#9]
Can you please provide a definitions file for typescript? http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Here is a great repo: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by roddeh** [comment]
I am unlikely to be able to get to this any time soon.  I would be happy to review a PR.

**Comment by kaliinmtrx** [comment]
I can provide ones, but looks like you have no Typescript files yet to make definitions for.

**Comment by gregBerthelot** [comment]
Yes looks like you should PR the TS files as well

**Comment by vishnuvardhana** [comment]
@kaliinmtrx PR for typescript files are also needed , let me know if I can assist .. not fully aware of the process of creating definitions, happy to learn.

**Comment by roddeh** [comment]
Does setting up a definition file require the project to be converted to TS?

Or is it possible to leave the library code as is and simply provide a definition file that describes the interfaces of what exists in JS?

I am not opposed to converting the project to TS, just wanting to reduce the scope of the initial PR to get it working nicely with TS.

**Comment by vishnuvardhana** [comment]
We are ok with having definitions separately need not convert entire library, type definitions @types/roddeh-i18n will be great .

**Comment by vishnuvardhana** [comment]
I am sure we can set up types without converting the project.

**Comment by gregBerthelot** [comment]
This should help https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by roddeh** [comment]
Ok, cool.  Thanks for clarifying.  @vishnuvardhana @kaliinmtrx are either of you able to setup the definitions as a PR?

**Comment by gregBerthelot** [comment]
@kaliinmtrx do you need help?

**Comment by Gesh4o** [comment]
Hey guys, do you still need help on this one?

**Comment by gregBerthelot** [comment]
@Gesh4o seems that nobody has move forward yet. I need it but I am not in position to help on this. @vishnuvardhana I am sure can If you can start something

**Comment by Gesh4o** [comment]
I will look at your docs and file a PR, would that be ok?

**Comment by gregBerthelot** [comment]
That would be great 👍

**Comment by vishnuvardhana** [comment]
@Gesh4o  thank you once you start I will be able to help you.

**Comment by Gesh4o** [comment]
I was about to open a PR today but I guess it doesn't matter now :/

**Comment by roddeh** [comment]
@evilarceus thanks for submitting the PR.  It looks good to me.  But @vishnuvardhana @Gesh4o, perhaps you could also take a look given you have more experience with TS definitions.

**Comment by Gesh4o** [comment]
I think @evilarceus has done a good job. However I cannot give my recommendations about the typescript definitions themselves but here are several improvements that could be made:

1. Create _tslint.config_ and _index.spec.ts_ (generally ts definitions come as 4 files - look at: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express)

2. Include two new commands: _lint:definitions_ and _test:definitions_ (could be named differently ofc) and **include** them in your **CI flow**. You will have to maintain that piece of code so make sure to avoid regressions as much as possible.

3. Keep an eye for private methods - they should not be included in definitions.

**Comment by evilarceus** [comment]
I added the changes for testing and linting to the pull request. Currently, it uses `dtslint`, meaning that it can't do linting only: `lint:typings` does both linting and testing, and `test:typings` only does testing. The scripts might need to be renamed or combined to make it more accurate. If we wanted, we could use `tslint` for linting only and then use `dtslint` for testing (or use a different testing system, though we are still only testing types).

Private methods were not included in the definitions, assuming all functions below `translateText()` (excluding `create()`, that's included in the definitions) are private.

As for CI flow: I don't believe this project has CI integration.

**Comment by roddeh** [comment]
Thanks for the contributions @evilarceus.  Merged ;)
